name: payuung
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build_runner: any
  cached_network_image: any
  cupertino_icons: any
  dartz: any
  flutter_native_splash: any
  flutter_svg: any
  get: any
  hive: any
  hive_flutter: any
  image_picker: any
  intl: any
  json_serializable: any
  path: any
  path_provider: any
  permission_handler: any
  shared_preferences: any
  sliding_up_panel: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any
  hive_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#FAC73C"
  android_12:
    color: "#FAC73C"